name: Build, Test and Publish release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x.x
          
      
    - name: install workloads
      run: dotnet workload restore src/Echoes.sln
      
    - name: Build for release
      run: dotnet build src/Echoes/Echoes.csproj -c Release

    - name: Build for release
      run: dotnet build src/Echoes.Avalonia/Echoes.Avalonia.csproj -c Release
      
    - name: Build for release
      run: dotnet build src/Echoes.Generator/Echoes.Generator.csproj -c Release
      
    - name: Publish Packages (if this version was not published before)
      run: dotnet nuget push src/**/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
